server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : student-service
          uri: http://localhost:8045
          predicates:
            - Path=/student/**
        - id: cti-service
          uri: http://localhost:8050
          predicates:
            - Path=/cti/**
